### ISSUE TITLE
gist backup

### ISSUE THREAD

**Issue by jorinvo** [jorinvo/github-backup#14]
Have to figure out how to do this first

**Comment by danieldiekmeier** [comment]
This would probably be a good starting point: `https://developer.github.com/v3/gists/#list-a-users-gists`

The script should
- Get a list of gists
- For each gist
    - Load each file in `files` from raw.github.com
    - Save with the filename

**Comment by jorinvo** [comment]
I was thinking about this again.
For me this doesn't feel like in the scope of this project. 
Adding options for the gist backup would bring to much complexity distracting the original mission.
I would prefer a separate command line tool for this.
