### ISSUE TITLE
automatic versioning

### ISSUE THREAD

**Issue by jorinvo** [jorinvo/github-backup#29]
https://www.atatus.com/blog/golang-auto-build-versioning/

Wait for https://github.com/goreleaser/releaser/issues/5

**Comment by caarlos0** [comment]
`main.version` is already set in goreleaser ldflags =)

**Comment by jorinvo** [comment]
@caarlos0 awesome! Thanks for letting me know!
I didn't realize Github will create a reference on your issue 😉
