### ISSUE TITLE
git remote update --progress gives error: unknown option `progress'

### ISSUE THREAD

**Issue by Strubbl** [jorinvo/github-backup#39]
On using ghbackup i get the following error, which i can reproduce on switching to the directory and issuing the command manually:

```
github/Strubbl/guayadeque.git[BARE:master]$ LANG=en git remote update --progress
error: unknown option `progress'
usage: git remote update [<options>] [<group> | <remote>]...

    -p, --prune           prune remotes after fetching
github/Strubbl/guayadeque.git[BARE:master]$ git version
git version 2.14.2
```

Is there any requirement i am missing? Wrong git version?

**Comment by jorinvo** [comment]
Thanks for reporting!
I added that flag in https://github.com/qvl/ghbackup/commit/1d2b3c45f103585b0d2aff69b205c94b27a2b911 to generate the statistics from the Git output. 
I will look into why it is not working.
For now you can use this version https://github.com/qvl/ghbackup/releases/tag/v1.10.

**Comment by jorinvo** [comment]
Seems like I added the `--progress` flag wrongly also to `remote update`. It is only required for `clone` since there we otherwise don't get the right output.
Could you try out https://github.com/qvl/ghbackup/releases/tag/v1.11.2 @Strubbl?

**Comment by Strubbl** [comment]
That was very fast. Thanks a lot. I cannot reproduce the issue with that version anymore.
