### ISSUE TITLE
Faulty statement about "Unchanged" repos

### ISSUE THREAD

**Issue by kMikaZu** [jorinvo/github-backup#41]
The Verbose output of the backup always returns this: 

`done: 0 new, 0 updated, 44 unchanged, 0 total objects`

But that's not correct. What do you need from us to investigate this?

**Comment by jorinvo** [comment]
hi @kMikaZu! I was wondering the same thing myself! Just never got around looking into it :) I think I solved it. But I had to remove the `total object` part from the info.

Could you [v.1.12.0](https://github.com/qvl/ghbackup/releases/tag/v1.12.0)?
Thank you!

**Comment by kMikaZu** [comment]
Hi @jorinvo 

Thanks, I give it a try today and keep you posted. 

Kind regards
Mika

**Comment by kMikaZu** [comment]
We are sending the statistics via a Slack WebHook. At first we used the option from your [tutorial](https://jorin.me/automating-github-backup-with-ghbackup/) and that works, but the text doesn't contain the statistics. 

Code from your tutorial: 

```
/opt/ghbackup -secret $github_token $backup_dir \
  && curl -X POST --data-urlencode \
  "payload={\"text\": \"Successful GitHub backup.\"}" \
  $slack_hook
```

On this GitHub page, you are explaining how to send more statistics to Slack, like this: 

```
ghbackup -secret $GITHUB_TOKEN DIR \
  | tail -n1 \
  | xargs -I%% curl -s -X POST --data-urlencode 'payload={"text": "%%"}' $SLACK_HOOK
```

But that doesn't seem to work on Debian 9. Keeps returning the following error: `curl: no URL specified!`

What would you suggest when using the script on a Debian machine? 

Thanks

**Comment by jorinvo** [comment]
the error message sounds like you didn't set the `SLACK_HOOK` variable? Maybe you set `slack_hook` instead? Make sure all variables exist and cases match :)

**Comment by kMikaZu** [comment]
Hi

The Slack Hook is defined, since the code from your tutorial works but the code from your GitHub Docs returns that error. 

Thanks

**Comment by jorinvo** [comment]
In the upper snipped you have `$slack_hook` in the lower `$SLACK_HOOK`. I guess I would need to see more of the code that you use to help you here..

**Comment by kMikaZu** [comment]
Ok, that one I misunderstood! You were right about it, it works. Case-Sensitive :-)
And the log mentions the updated Repos now. Seems to work ok, but will do some more testing. Is it possible to add even more statistics (a complete backup-report of all the repos?)? 

Thanks!

**Comment by jorinvo** [comment]
If you want to post all output to Slack and not only the statistics, you can skip the line `| tail -n1 \`. Not sure if that is enough information. Let me know what other kind of statistics you are looking for!

**Comment by jorinvo** [comment]
@kMikaZu if you have any suggestions to other statistics/details we should output, let me know! Can open a new issue for it 🙂

**Comment by kMikaZu** [comment]
The LFS issue is more important at this time, afterwards we can pick up the statistics. But thanks a lot!!
