### ISSUE TITLE
LFS (Large File Support)

### ISSUE THREAD

**Issue by kMikaZu** [jorinvo/github-backup#42]
Hi

Apparently, ghbackup doesn't support LFS? 

Thanks

**Comment by jorinvo** [comment]
hi, I have never worked with LFS. As far as I can tell it's simple an extension you install but all your git commands still work like normal?

Under the hood ghbackup executes the `git` binary available on your system. If `git` has LFS installed, it should work.

**Comment by kMikaZu** [comment]
Hi

LFS was installed and added to git, bit it doesn't work.

**Comment by jorinvo** [comment]
is there any error message? or do you have a way for me to reproduce it? it do not have any LFS things myself.

**Comment by pieterclaerhout** [comment]
The things is that there is no error messages, but the large files are not checked out.

Fixing this should be rather simple (provided you have the git-lfs commands installed as instructed on https://git-lfs.github.com.

Once you have them installed, it's probably just a matter of changing:

```
git checkout ...
```

to:

```
git lfs checkout ...
```

You can read more about it on:

* https://github.com/git-lfs/git-lfs/tree/master/docs
* https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-clone.1.ronn

**Comment by jorinvo** [comment]
`ghbackup` is not not using `git checkout` but `clone` and `remote update`.
I guess those also work in `lfs` mode...

The code is super simple in case you want to have a look: 
https://github.com/qvl/ghbackup/blob/master/ghbackup/backup.go#L34-L38

Would need to find a way to find out for each repository wether to use `git` or `git lfs` I guess. Is there anyway to tell which mode a repository is using?
We get the repo information from the API. For example: https://api.github.com/users/qvl/repos?per_page=100
I don't see any indication if a repository is `lfs` though...

Any ideas?

**Comment by pieterclaerhout** [comment]
The command should be interchangeable, so I guess the question is more on how you can check if the user has the Git LFS tools installed vs. whether the repositories are using LFS.

You could also check the `.gitattributes` file in the root of the repo to see if LFS is used. If the repository is using LFS, it will contains lines like:

```
*.mmdb filter=lfs diff=lfs merge=lfs -text
```

**Comment by jorinvo** [comment]
Sounds simple enough. Would be happy to extend ghbackup with LFS support! 

I don't have much spare time at the moment and I cannot really test LSF myself. Would be really happy getting some help with this 🙂

This would simply require figuring out how to detect if LSF is available and choosing the git command accordingly.

**Comment by pieterclaerhout** [comment]
What about checking if the `git-lfs` executable is somewhere in the PATH environment variable using [`exec.LookPath`](https://golang.org/pkg/os/exec/#LookPath)?

**Comment by jorinvo** [comment]
hi there, as you might have guessed I don't have time or needs for implementing this feature at the moment. You are welcome to send a Pull Request if you are still interested in adding git-lfs support. I would gladly accept it. Thanks for understanding.
